### ISSUE TITLE
Huge optimisation issue

### ISSUE THREAD

**Issue by Jaffies** [danx91/SCP-LC#27]
Need to do:

1. Color caching
2. ipairs instead of pairs when iterating with sequenced tables (ex. player.GetAll())
3. net bandwitch fix (need to stop using net.WriteTable/ReadTable everywhere)
4. Rewrite cl_eq.lua using vgui instead of HUDPaint.
5. Either delete scp hud objects or rewrite them.
6. Make SCP skill object for use with scp hud object/serverside checks without using primaryattack() or secondaryattack() or smth. like that

**Comment by shockpast** [comment]
There is also other problems such as
1. Inconsistency in code styling:
   - `/* */` comments sometimes varied by `--[[ ]]`
   - Localized variables sometimes named as `VARIABLENAME`, sometimes `VARIABLE_NAME`, even `variable_name`
   - `draw.Text{}`, why tf there is no `()`...
2. Egyptian scopes, those `if` pyramids are just too fucking big
3. Follow the Lua naming, not Garry's one (`!` is bad, do `not`; `!=` is bad, do `~=`), it's just awful

**Comment by shockpast** [comment]
> 4. Rewrite `cl_eq.lua` using `vgui` instead of `HUDPaint`.
Is it actually needed... It's a good practice to use VGUI in HUD, but it's just a base, current base HUD looks like shit, it's not user-friendly, and very hard to interact with, it's better to left current and just let developers make their one on their servers.

**Comment by Jaffies** [comment]
Also there is a problem in creating classes with `__call` metamethods.
Some classes like `SLCPromise` uses `__call` metamethod and others, like `SCPSkillObject` uses standalone creation function.
I would prefer calling standalone function because most autocompleting plugins for sublime text (and other ide/text editors) don't support `__call` metamethods.
Also, there is a huge problem in understanding types of variables.
Inconsistency with ErrorWithNoHalt and assert functions
Really bad realisation of inventory system (at least in understanding how it works)

**Comment by danx91** [comment]
I commented on this already on Discord and forgot to include it here.

> Color caching

Done in most cases, there are only few places where colors are not cached. _Also, colors should be unpacked if we are trying to maximize the performance_.

> ipairs instead of pairs when iterating with sequenced tables (ex. player.GetAll())

It's not that bad as people tend to scream about it... (difference of 1/1000 of a second at tables with several thousands of entries) However it _might_ be slightly beneficial to use it in time critical functions. _Again, if performance is top priority then `for i=1, #tab` should be used_.

> net bandwitch fix (need to stop using net.WriteTable/ReadTable everywhere)

Imho, triumph of form over content. The gamemode is sending tables over network, but it's not used all the time, only few (most likely functions called only once per player) are using it. Additionally, it's only adding 2 bytes per key/value pair, so not that much considering the size of these tables - open `net_graph` and see that the engine itself is generating hundreds or even thousands times more net traffic. (Tables that _may_ be really big (in rare, very unlikely situations) are being sent using gmod wiki recommended way - convert to json, compress, split to ~64kb chunks and send).

>Rewrite cl_eq.lua using vgui instead of HUDPaint

As many may noticed, HUD looks like it looks - not really appealing (I'm not a designer after all). The only benefits of using VGUI over `HUDPaint` are (in my opinion): cached calculations (that are re-computed when needed) and better readability of the code. VGUI with all the function all _may_ even be slower. However, in all my new projects I'm using VGUI (mainly because of said readability), so new HUD will be made in VGUI (if it will be made). As stated by someone else, base HUD should be replaced by server owners anyway to make it consistent with their whole brand.

> Either delete scp hud objects or rewrite them

> Make SCP skill object for use with scp hud object/serverside checks without using primaryattack() or secondaryattack() or smth. like that

This was made as an experimental feature, still many things to change there.

>Also there is a problem in creating classes with `__call` metamethods

Personally, I prefer `__call` and as stated above `SCPSkillObject` is experimental l thing.

> Inconsistency with `ErrorWithNoHalt` and `assert` functions

The main goal was to use `ErrorWithNoHalt` in non-critical errors and either `assert` or `error` with critical ones, but yeah, it can be a little more consistent.

> Inconsistency in code styling

This was also explained on Discord... development of this gamemode started like 4 years ago and I changed my style fee times before I worked out my final preferred one. I won't waste time to refactor whole gamemode, just deal with that.

> danx91 or some contributors, occasionally uses `Color()` in `surface.SetDrawColor()`, read the **** notes

Already explained above, also stop using profanities it's neither elegant nor professional.

> Follow the Lua naming, not Garry's one (! is bad, do not; != is bad, do ~=), it's just awful

Why's that? Is there some security/performance/other critical issue that I should know about or is it just your delusion that everyone should follow the _only allowed and righteous_ code style? I just prefer `!`, as most of the developers do. EOT.

> Egyptian scopes, those if pyramids are just too **** big

Ok, I fully agree with this point and most (like 99%) of these pyramids can be eliminated by simple _if guards_ or `continue`s (but you wouldn't accept that either because it's not Lua standard keywor but Garry's evil one), but some can't be just removed without using even worse `goto` statements or creating special functions that will only serve a _remove-some-code-so-scope-is-not-that-deep_ purpose. I don't think that there is a problem with scope depth as long as it makes uniform and easy to follow "flow".

If you have more issues with my code, feel free to comment on that, but don't repeat yourself nor argue with my preferences. Also, please keep some standards, if you can't write without swearing, just don't write.

**Comment by danx91** [comment]
Most of the issues were fixed in commit 614336b, the remaining ones like rewriting HUD elements are not technically an issue

**Comment by danx91** [comment]
Most of the issues were fixed in commit 614336b, the remaining ones like rewriting HUD elements are not technically an issue.
